In [1]:
import numpy as np
import scipy
import random
import math

# Task 1

In [2]:
def task_3_a(n: int, m: int, r: int, c: int):
    result = np.ones((n, m), dtype=int)
    
    result[(np.arange(n)) % r == 0, :] = 0
    result[:, (np.arange(m)) % c == 0] = 0
    
    return result

In [3]:
def task_3_b(n: int, m: int, r: int, c: int):
    result = [[1] * m for _ in range(n)]
    
    for i in range(n):
        if i % r == 0:
            result[i] = [0] * m
    
    for j in range(m):
        if j % c == 0:
            for i in range(n):
                result[i][j] = 0
    
    return result

In [4]:
def task_5_a(n: int):
    result = np.ones((n, n), dtype=int)
    result[1::2] = 0
    
    return result

In [5]:
def task_5_b(n: int):
    result = []
    for i in range(n):
        if i % 2 == 0:
            result.append([1] * n)
        else:
            result.append([0] * n)
    
    return result

In [6]:
def task_7_a(arr: np.array):
    arr[arr == 0] = -1
    
    return arr

In [7]:
def task_7_b(arr: []):
    for i in range(len(arr)):
        if arr[i] == 0:
            arr[i] = -1
    
    return arr

In [8]:
def task_9_a(n: int):
    return np.arange(n, -1, -1)

In [9]:
def task_9_b(n: int):
    return list(range(n, -1, -1))

In [10]:
def task_10_a(n: int, m: int):
    matrix = np.random.rand(n, m)
    
    return np.min(matrix), np.max(matrix), np.mean(matrix), np.std(matrix)

In [11]:
def task_10_b(n: int, m: int):
    matrix = [[random.random() for _ in range(m)] for _ in range(n)]
    
    flattened_matrix = [val for sublist in matrix for val in sublist]
    
    min_val = min(flattened_matrix)
    max_val = max(flattened_matrix)
    average_val = sum(flattened_matrix) / len(flattened_matrix)
    std_dev = math.sqrt(sum((x - average_val) ** 2 for x in flattened_matrix) / len(flattened_matrix))
    
    return min_val, max_val, average_val, std_dev

In [12]:
def task_12_a(n: int):
    result = np.zeros((n, n), dtype=int)
    result[1:-1, 1:-1] = 1
    return result

In [13]:
def task_12_b(n: int):
    result = []
    for i in range(n):
        row = []
        for j in range(n):
            if i == 0 or i == n - 1 or j == 0 or j == n - 1:
                row.append(0)
            else:
                row.append(1)
        result.append(row)
    return result

In [14]:
def task_14_a():
    return np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

In [15]:
def task_14_b():
    result = []

    for i in range(8):
        row = []

        for j in range(8):
            if i % 2 == 0:
                if j % 2 == 0:
                    row.append(0)
                else:
                    row.append(1)
            else:
                if j % 2 == 0:
                    row.append(1)
                else:
                    row.append(0)

        result.append(row)

    return result

In [16]:
def task_15_a(n: int):
    result = np.ones((n, n), dtype=int)

    result[:, ::2] = 0

    return result

In [17]:
def task_15_b(n: int):
    result = []

    for i in range(n):
        row = []

        for j in range(n):
            if j % 2 == 0:
                row.append(0)
            else:
                row.append(1)

        result.append(row)

    return result

In [18]:
def task_21_a(n: int, m: int):
    result = np.random.randint(0, m, size=(n, n))

    max_val = np.max(result)

    result[result == max_val] *= -1

    return result

In [19]:
def task_21_b(n: int, m: int):
    result = [[random.randint(0, m - 1) for _ in range(n)] for _ in range(n)]

    max_val = max(max(row) for row in result)

    for i in range(n):
        for j in range(n):
            if result[i][j] == max_val:
                result[i][j] *= -1

    return result

In [20]:
task_3_a(6, 7, 2, 3)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0]])

In [21]:
%timeit task_3_a(6, 7, 2, 3)

14.5 µs ± 174 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
task_3_b(6, 7, 2, 3)

[[0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0]]

In [23]:
%timeit task_3_b(6, 7, 2, 3)

2.86 µs ± 28 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
task_5_a(5)

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [25]:
%timeit task_5_a(5)

2.15 µs ± 28.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [26]:
task_5_b(5)

[[1, 1, 1, 1, 1],
 [0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1],
 [0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1]]

In [27]:
%timeit task_5_b(5)

1.01 µs ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [28]:
task_7_a(np.array([0, 0, 2, 3, 4]))

array([-1, -1,  2,  3,  4])

In [29]:
%timeit task_7_a(np.array([0, 0, 2, 3, 4]))

3.01 µs ± 41.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [30]:
task_7_b([0, 0, 2, 3, 4])

[-1, -1, 2, 3, 4]

In [31]:
%timeit task_7_b([0, 0, 2, 3, 4])

379 ns ± 5.06 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [32]:
task_9_a(10)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [33]:
%timeit task_9_a(10)

819 ns ± 26.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [34]:
task_9_b(10)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [35]:
%timeit task_9_b(10)

333 ns ± 81.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [36]:
%precision 3
task_10_a(5, 5)

(0.101, 0.938, 0.525, 0.251)

In [37]:
%timeit task_10_a(5, 5)

49.3 µs ± 4.53 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [38]:
%precision 3
task_10_b(5, 5)

(0.074, 0.970, 0.575, 0.302)

In [39]:
%timeit task_10_b(5, 5)

9.4 µs ± 69 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [40]:
task_12_a(4)

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [41]:
%timeit task_12_a(4)

1.16 µs ± 15.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [42]:
task_12_b(4)

[[0, 0, 0, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]]

In [43]:
%timeit task_12_b(4)

2.1 µs ± 36.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [44]:
task_14_a()

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [45]:
%timeit task_14_a()

6.08 µs ± 243 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [46]:
task_14_b()

[[0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0]]

In [47]:
%timeit task_14_b()

7.37 µs ± 97.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
task_15_a(5)

array([[0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

In [49]:
%timeit task_15_a(5)

2.23 µs ± 20.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [50]:
task_15_b(5)

[[0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0]]

In [51]:
%timeit task_15_b(5)

2.56 µs ± 22.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [52]:
task_21_a(4, 10)

array([[ 6, -9, -9,  8],
       [ 2,  1,  7,  0],
       [ 0,  3,  8,  7],
       [ 8,  4,  2,  6]])

In [53]:
%timeit task_21_a(4, 10)

17 µs ± 65.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [54]:
task_21_b(4, 10)

[[3, 7, 8, 2], [-9, 3, 6, 8], [7, 8, 3, 0], [5, 0, 8, 0]]

In [55]:
%timeit task_21_b(4, 10)

10.5 µs ± 48.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Task 2

In [56]:
A = np.array([[1, 3, 5, 7],
              [3, 5, 7, 1],
              [5, 7, 1, 3],
              [7, 1, 3, 5]])

B = np.array([12, 0, 4, 16])

In [57]:
def solution_cramer(a, b):
    n = len(b)
    det_a = np.linalg.det(a)
    x = np.zeros(n)
    for i in range(n):
        a_temp = A.copy()
        a_temp[:, i] = b
        x[i] = np.linalg.det(a_temp)/ det_a
    return x

In [58]:
def solution_matrix_multiplication(a, b):
    p, l, u = scipy.linalg.lu(a)

    pb = p @ b
    y = np.linalg.solve(l, pb)

    return np.linalg.solve(u, y)

In [59]:
def solution_inverse_matrix(a, b):
    return np.linalg.inv(a) @ b

In [60]:
def solution_numpy_linalg_solve(a, b):
    return np.linalg.solve(a, b)

In [61]:
solution_cramer(A, B)

array([ 1.000e+00, -1.000e+00, -1.249e-16,  2.000e+00])

In [62]:
solution_matrix_multiplication(A, B)

array([ 1.000e+00, -1.000e+00, -1.018e-16,  2.000e+00])

In [63]:
solution_inverse_matrix(A, B)

array([ 1.00e+00, -1.00e+00, -2.22e-16,  2.00e+00])

In [64]:
solution_numpy_linalg_solve(A, B)

array([ 1.000e+00, -1.000e+00, -1.018e-16,  2.000e+00])

In [65]:
np.allclose(solution_cramer(A, B), solution_matrix_multiplication(A, B))

True

In [66]:
np.allclose(solution_matrix_multiplication(A, B), solution_inverse_matrix(A, B))

True

In [67]:
np.allclose(solution_inverse_matrix(A, B), solution_numpy_linalg_solve(A, B))

True

# Task 3

In [68]:
A = np.array([[5, 2, 0],
              [10, 4, 1],
              [7, 3, 2]])

B = np.array([[3, 6, -1],
              [-1, -2, 0],
              [2, 1, 3]])

In [69]:
def solution_numpy(a, b):
    return (a - b @ b) * (2 * a + b)

In [70]:
def solution_iterative(a, b):
    result = []
    for i in range(len(a)):
        row = []
        for j in range(len(a[0])):
            element = (a[i][j] - sum(b[i][k] * b[k][j] for k in range(len(b)))) * (2 * a[i][j] + b[i][j])
            row.append(element)
        result.append(row)
    return result

In [71]:
solution_numpy(A, B)

array([[ 52, -30,  -6],
       [209,  36,   0],
       [-64, -70, -35]])

In [72]:
%timeit solution_numpy(A, B)

4.56 µs ± 39.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [73]:
solution_iterative(A, B)

[[52, -30, -6], [209, 36, 0], [-64, -70, -35]]

In [74]:
%timeit solution_iterative(A, B)

28 µs ± 870 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [75]:
np.allclose(solution_numpy(A, B), solution_iterative(A, B))

True